### ISSUE TITLE
Main and gh-pages branches have diverged

### ISSUE THREAD

**Issue by mwhamgenomics** [carpentries-incubator/python-novice-programming-gapminder#36]
These two branches have been updated independently since October 2021, meaning that there are unpublished updates in main, and what is immediately visible in GitHub doesn't represent the published material. Is this intentional?

I also notice that CONTRIBUTING.md says to submit PRs against gh-pages, but discussions elsewhere on Slack say that this is intended for GitHub Actions, and PRs should be made against main. Can I confirm what branches to use?

**Comment by jsteyn** [comment]
Apologies for the late reply. I am trying to sort all this out now.

**Comment by jsteyn** [comment]
Main has now been merged into gh-pages
